name: Simple APK Build
on:
  workflow_dispatch:
    inputs:
      app_name:
        description: 'Name'
        required: true
      app_url:
        description: 'URL'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build With Global Tool
        run: |
          # هنا نستخدم أداة بسيطة ما تحتاج مستودع معقد
          npm install -g nativefier
          nativefier "${{ github.event.inputs.app_url }}" --name "${{ github.event.inputs.app_name }}" --platform android
          
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: my-app
          path: ./*.apk
