name: ADA PLUS GENERATOR
on:
  workflow_dispatch:
    inputs:
      app_name:
        description: 'اسم التطبيق'
        required: true
      app_url:
        description: 'رابط الموقع'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Builder Tool
        run: npm install -g nativefier

      - name: Create APK
        run: |
          nativefier "${{ github.event.inputs.app_url }}" \
          --name "${{ github.event.inputs.app_name }}" \
          --platform android

      - name: Upload Finished APK
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.app_name }}
          path: ./*.apk
