name: ADA Plus - Ultimate APK Generator
on:
  workflow_dispatch:
    inputs:
      app_name:
        description: 'App Name'
        required: true
      app_url:
        description: 'App URL'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Generate APK from Webview Template
        uses: abbasfargad/webview-apk-action@main # هذا مثال لمكتبة جاهزة
        with:
          name: ${{ github.event.inputs.app_name }}
          url: ${{ github.event.inputs.app_url }}

      - name: Release APK
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          files: ./*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
